### ISSUE TITLE
Site needs a favicon

### ISSUE THREAD

**Issue by DanielRyanSmith** [GabriellaMSanchez/trails#3]
The favicon for the site was removed in PR #2. It needs to be replaced with a more apt icon.

cc @GabriellaMSanchez

**Comment by GabriellaMSanchez** [comment]
Added this in[ this pull request](https://github.com/GabriellaMSanchez/trails/pull/7)! Thank you for pointing it out.

**Comment by GabriellaMSanchez** [comment]
Fixed in #7
